name: Deploy Static Site
on:
  push:
    branches: [main]
permissions:
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false # Isso previne o erro de submodules

      - name: Setup Pages
        uses: actions/configure-pages@v4 # Versão atualizada

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3 # Versão nova!
        with:
          path: './'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 # Versão atualizada